namespace XtraUpload.Domain
{
    /// <summary>
    /// Operation result state
    /// </summary>
    public enum OperationState
    {
        Success,
        Warning,
        Failed,
    }

    /// <summary>
    /// Error origin
    /// </summary>
    public enum ErrorOrigin
    {
        None,
        /// <summary>
        /// The error is generated by the server
        /// </summary>
        Server,
        /// <summary>
        /// The error is caused by the client
        /// </summary>
        Client
    }

    /// <summary>
    /// User claims
    /// </summary>
    public enum XtraUploadClaims : ushort
    {
        /// <summary>
        /// Access to admin panel
        /// </summary>
        AdminAreaAccess,
        /// <summary>
        /// Access to file manager panel
        /// </summary>
        FileManagerAccess,
        /// <summary>
        /// File expiration time (expired files will be deleted) (int - days)
        /// </summary>
        FileExpiration,
        /// <summary>
        /// Time to wait before download link is generated (int seconds)
        /// </summary>
        WaitTime,
        /// <summary>
        /// Time to wait before requesting a new download (int seconds)
        /// </summary>
        DownloadTTW,
        /// <summary>
        /// Storage space (int Mb)
        /// </summary>
        StorageSpace,
        /// <summary>
        /// How many files a user can upload at once (int)
        /// </summary>
        ConcurrentUpload,
        /// <summary>
        /// Max download speed (int kb)
        /// </summary>
        DownloadSpeed,
        /// <summary>
        /// Max file size to upload (int Mb)
        /// </summary>
        MaxFileSize
    }
    /// <summary>
    /// Login providers
    /// </summary>
    public enum AuthProvider : ushort
    {
        STANDARD,
        GOOGLE,
        FACEBOOK
    }

    /// <summary>
    /// Request status
    /// </summary>
    public enum RequestStatus
    {
        /// <summary>
        /// The request is in Progress
        /// </summary>
        InProgress,
        /// <summary>
        /// The request completed
        /// </summary>
        Completed,
        /// <summary>
        /// Request timed out
        /// </summary>
        TimedOut,
        /// <summary>
        /// The request has failed
        /// </summary>
        Failed
    }
    /// <summary>
    /// Available themes
    /// </summary>
    public enum Theme : ushort
    {
        Dark,
        Light
    }
    /// <summary>
    /// Thumbnail size
    /// </summary>
    public enum ThumbnailSize
    {
        Small,
        Medium,
        Avatar
    }
    /// <summary>
    /// Item (file or folder) status
    /// </summary>
    public enum ItemStatus
    {
        /// <summary>
        /// The item is visible, users can view, download, share.. the item
        /// </summary>
        Visible,
        /// <summary>
        /// The item is hidden from other users, but visible for the owner
        /// </summary>
        Hidden,
        /// <summary>
        /// Marks an item to be processed (image resizing, video converting...)
        /// </summary>
        To_Be_Processed,
        /// <summary>
        /// Marks an item to be deleted
        /// </summary>
        To_Be_Deleted
    }

    public enum ServerState
    {
        /// <summary>
        /// Server is down/unreachable
        /// </summary>
        Unknown,
        /// <summary>
        /// Uploads and downloads are enabled
        /// </summary>
        Active,
        /// <summary>
        /// Downloads are available, uploads are disabled
        /// </summary>
        Passive,
        /// <summary>
        /// Server is reachable, but no uploads/downloads are allowed
        /// </summary>
        Disabled,
    }
}
