using System;
using System.Collections.Generic;

namespace XtraUpload.Domain
{
    /// <summary>
    /// Represent a file
    /// </summary>
    public class FileItem: ItemInfo
    {
        public FileItem()
        {
            Downloads = new HashSet<Download>();
        }
        
        /// <summary>
        /// Id generated by the tus uplaod api
        /// </summary>
        public string TusId { get; set; }
        /// <summary>
        /// Mime type
        /// </summary>
        public string MimeType { get; set; }
        /// <summary>
        /// Mime type
        /// </summary>
        public string Extension { get; set; }
        /// <summary>
        /// Total downloads of the file
        /// </summary>
        public int DownloadCount { get; set; }
        /// <summary>
        /// Size of the file in bytes
        /// </summary>
        public long Size { get; set; }

        public virtual string FolderId { get; set; }
        public virtual Guid StorageServerId { get; set; }
        public virtual FolderItem Folder { get; set; }
        public virtual StorageServer StorageServer { get; set; }
        public virtual ICollection<Download> Downloads { get; set; }
    }
}
